version: "2.1"

services:
  deluge:
    image: ghcr.io/linuxserver/deluge
    volumes:
      - deluge-config:/config
      - ./core.conf:/config/core.conf
  storm:
    build: .
    environment:
      DELUGE_RPC_VERSION: v2
      DELUGE_RPC_HOSTNAME: deluge
      DELUGE_RPC_USERNAME: localclient
      DELUGE_RPC_PASSWORD: 707228f42b81e12377e943271f8c05b796545cd2
    ports:
      - "8221:8221"

volumes:
  deluge-config: