version: "2.1"

services:
  deluge:
    image: ghcr.io/linuxserver/deluge
    volumes:
      - deluge-config:/config
      - ./core.conf:/config/core.conf
      - ./auth:/config/auth:ro
  storm:
    image: ghcr.io/relvacode/storm
    environment:
      DELUGE_RPC_VERSION: v2
      DELUGE_RPC_HOSTNAME: deluge
      DELUGE_RPC_USERNAME: localclient
      DELUGE_RPC_PASSWORD: deluge
    ports:
      - "8221:8221"

volumes:
  deluge-config: